/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class MATH_CLASS */

#ifndef _Included_MATH_CLASS
#define _Included_MATH_CLASS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MATH_CLASS
 * Method:    T
 * Signature: (DDDDDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_MATH_1CLASS_T
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
